### ISSUE TITLE
GitHub action to set up Liberica NIK?

### ISSUE THREAD

**Issue by chirontt** [bell-sw/Liberica#103]
Is there a GitHub action to set up Liberica NIK to use in GitHub workflows?

**Comment by chirontt** [comment]
Answering my own question: No, not specific to Liberica NIK distribution.

But there is an existing [setup-java](https://github.com/actions/setup-java) action which can be used to set up the Liberica NIK in GitHub workflows, as followed:
```yaml
    steps:
      - name: Download Liberica NIK 22.3.0 for Java 17 (Linux)
        run: |
          download_url="https://download.bell-sw.com/vm/22.3.0/bellsoft-liberica-vm-core-openjdk17.0.5+8-22.3.0+2-linux-amd64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Set up Liberica NIK 22.3.0 for Java 17 (Linux)
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: 17
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          architecture: x64
```
